### ISSUE TITLE
Radio_slider_shape.dart paint method fails on build

### ISSUE THREAD

**Issue by pcostigan** [adaptant-labs/flutter_radio_slider#1]
I think that a recent upgrade to Flutter broke the pain method. I received the message that the paint method did not contain the 'sizeWithOverFlow' parameter. I change your paint method by adding both 'double textScaleFactor, Size sizeWithOverflow to the end of the paint constructor. This fixed the issue.

**Comment by pmundt** [comment]
Thanks for the feedback, if you've already fixed this, can you open a PR for it?

**Comment by pcostigan** [comment]
Hi Paul, 

 

I am not new to programming but I am new to all this GitHub stuff. I do not have a GitHub account and do not know what a PR is. 

 

Pat

**Comment by pmundt** [comment]
@pcostigan No problem, it turns out this was a breaking API change in flutter, so I've also had to bump up the minimum version. I'll cut a new 0.0.2 release with this fixed. Thanks again.
